import os

file_path = os.path.join("src", "styles", "tokens.css")

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Keep lines 0-777 (1-indexed lines 1-778) which are clean
clean_lines = lines[:778]

# The new tail to append
tail_lines = [
    "\n",
    ".portal-main .bg-blue-50,\n",
    ".portal-main .bg-blue-50\\/40,\n",
    ".portal-main .bg-blue-50\\/50,\n",
    ".portal-main .bg-blue-100,\n",
    ".portal-main .bg-\\[\\#F0F7FD\\],\n",
    ".portal-main .bg-\\[\\#E8F4FD\\],\n",
    ".portal-main .bg-\\[\\#F4F8FF\\] {\n",
    "  background-color: rgba(127, 160, 214, 0.12) !important;\n",
    "  color: #BCCCE6 !important;\n",
    "  border-color: #2A3446 !important;\n",
    "}\n",
    "\n",
    ".portal-main .bg-\\[\\#0052FF\\],\n",
    ".portal-main .bg-\\[\\#2B7BC4\\],\n",
    ".portal-main .bg-\\[\\#1E609A\\] {\n",
    "  background-color: #BCCCE6 !important;\n",
    "  color: #0B111C !important;\n",
    "  font-weight: 700 !important;\n",
    "}\n",
    "\n",
    ".portal-main .hover\\:bg-\\[\\#0045D8\\]:hover,\n",
    ".portal-main .hover\\:bg-\\[\\#1A5EA8\\]:hover {\n",
    "  background-color: #FFFFFF !important;\n",
    "  color: #0B111C !important;\n",
    "}\n",
    "\n",
    ".portal-main .border-\\[\\#0052FF\\],\n",
    ".portal-main .border-\\[\\#2B7BC4\\],\n",
    ".portal-main .border-blue-100,\n",
    ".portal-main .border-blue-200 {\n",
    "  border-color: #2A3446 !important;\n",
    "}\n",
    "\n",
    "/* ==========================================================================\n",
    "   NEBULA BENTO THEME \u2014 Scoped to .bento-theme wrapper\n",
    "   Only affects Client Portal & Onboarding pages.\n",
    "   ========================================================================== */\n",
    "\n",
    ":root {\n",
    "  --nebula-void: #050810;\n",
    "  --nebula-navy: #0B111C;\n",
    "  --nebula-surface: #161F2D;\n",
    "  --nebula-steel: #2A3446;\n",
    "  --nebula-mist: #97A0B3;\n",
    "  --nebula-periwinkle: #BCCCE6;\n",
    "  --nebula-glow: #7FA0D6;\n",
    "  --nebula-sand: #D8BF9B;\n",
    "}\n",
    "\n",
    "/* --- Remove all shadows inside bento-theme --- */\n",
    ".bento-theme *,\n",
    ".bento-theme *::before,\n",
    ".bento-theme *::after {\n",
    "  box-shadow: none !important;\n",
    "}\n",
    "\n",
    '/* --- Remove all gradients inside bento-theme --- */\n',
    '.bento-theme [class*="bg-gradient-"],\n',
    '.bento-theme [class*="from-"],\n',
    '.bento-theme [class*="via-"] {\n',
    "  background-image: none !important;\n",
    "}\n",
    "\n",
    "/* --- Hide decorative blur glows --- */\n",
    '.bento-theme [class*="blur-3xl"],\n',
    '.bento-theme [class*="blur-2xl"],\n',
    ".bento-theme .animate-ai-bg-drift,\n",
    ".bento-theme .animate-ai-orb-1,\n",
    ".bento-theme .animate-ai-orb-2 {\n",
    "  display: none !important;\n",
    "}\n",
    "\n",
    "/* --- Remove backdrop-filter (frosted glass) --- */\n",
    '.bento-theme [class*="backdrop-blur"] {\n',
    "  backdrop-filter: none !important;\n",
    "  -webkit-backdrop-filter: none !important;\n",
    "}\n",
    "\n",
    "/* --- Remove hover lift transforms for flat bento feel --- */\n",
    ".bento-theme .card-interactive:hover,\n",
    ".bento-theme .hover\\\\:-translate-y-1:hover,\n",
    '.bento-theme [class*="hover:-translate-y"]:hover {\n',
    "  transform: none !important;\n",
    "}\n",
]

with open(file_path, "w", encoding="utf-8") as f:
    f.writelines(clean_lines)
    f.writelines(tail_lines)

print("Done! tokens.css rebuilt cleanly.")
